#!/bin/bash
#

clear
echo -e "\n\033[1;36m  REMOVER ARQUIVOS INUTES\033[1;33m"
cd /var/www/html/ && rm -f EnviarAdicionarCriarTeste.php*
sleep 1
cd /var/www/html/ && rm -f usuario.php*
sleep 1
echo -e "\n\033[1;36m  INICIANDO ATUALIZACAO PODE DEMORAR\033[1;33m"
cd /var/www/html/
    wget https://raw.githubusercontent.com/vpn-ssh/PWEB4G/main/usuario.php > /dev/null 2>&1
sleep 1
cd /var/www/html/
   wget https://raw.githubusercontent.com/vpn-ssh/PWEB4G/main/EnviarAdicionarCriarTeste.php > /dev/null 2>&1
sleep 1
echo -e "           \033[1;33m● \033[1;32mREINICIA O APACHE2 \033[1;33m●\033[0m"
 service apache2 restart
