#!/bin/bash
#
echo -e "\n\033[1;36m  INICIANDO ATUALIZACAO PODE DEMORAR\033[1;33m"
cd /var/www/html/
    wget https://github.com/vpn-ssh/PWEB4G/archive/refs/heads/main.zip > /dev/null 2>&1
sleep 1
unzip main.zip > /dev/null 2>&1
rm -rf main.zip index.html > /dev/null 2>&1
service apache2 restart
